[metadata]
license_files = LICENSE
name = chromatrace
description = Advanced logging for Python

[tool.ruff]
line-length = 100
target-version = "py37"
ignore = ["E501"]  # line length

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True